apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: arbout-migrate
spec:
  schedule: "0 0 1 * 0"
  suspend: true # this is only used as a --from= for jobs, hence doesn't run auto
  # backoffLimit: 1 # is this not supported in v1beta1?
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: migrate
            image: arbout-migrate
            command: [automig_pg, update]
            env:
            - name: AUTOMIG_GLOB
              value: schema/*.sql
            - name: AUTOMIG_CON
              valueFrom: {secretKeyRef: {name: arbout-secrets, key: db_url}}
            - name: PGCONNECT_TIMEOUT
              value: "10"
          imagePullSecrets:
          - name: regcred
