build:
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  script:
  - docker build -t $IMAGE_TAG -f prod.Dockerfile .

test:
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE/test:$CI_COMMIT_SHORT_SHA
  script:
  - docker build -t $IMAGE_TAG .
  - docker run --rm $IMAGE_TAG pylint lib
  - docker run --rm $IMAGE_TAG mypy lib
  - docker run --rm $IMAGE_TAG pytest

deploy:
  environment: local
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  when: manual
  script:
  - docker rm -fv arbout
  - docker run -d --name arbout -e ARB_SALT=$ARB_SALT -p $ARB_PORT:8000 $IMAGE_TAG
